# Generated by Django 5.0.3 on 2024-04-17 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('review', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('written', models.ManyToManyField(related_name='written_place', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
