# Generated by Django 5.0.3 on 2024-04-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.CharField(max_length=30)),
                ('public', models.BooleanField()),
                ('review', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_placepost', to=settings.AUTH_USER_MODEL)),
                ('recommended', models.ManyToManyField(related_name='recommended_placepost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_placecomment', to=settings.AUTH_USER_MODEL)),
                ('recommended', models.ManyToManyField(related_name='recommended_placecomment', to=settings.AUTH_USER_MODEL)),
                ('placepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placepost')),
            ],
        ),
    ]
