# Generated by Django 5.0.3 on 2024-04-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_placecomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='recommended',
            field=models.ManyToManyField(related_name='recommended_placecomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_placepost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placepost',
            name='recommended',
            field=models.ManyToManyField(related_name='recommended_placepost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='placepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placepost'),
        ),
    ]
