# Generated by Django 4.2.11 on 2024-04-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placepost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_placepost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placecomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_placecomment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placecomment",
            name="placepost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="place.placepost"
            ),
        ),
        migrations.AddField(
            model_name="placecomment",
            name="recommended",
            field=models.ManyToManyField(
                related_name="recommended_placecomment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
