# Generated by Django 5.0.3 on 2024-04-15 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepost',
            name='recommended',
            field=models.ManyToManyField(blank=True, default=0, related_name='recommended_placepost', to=settings.AUTH_USER_MODEL),
        ),
    ]
