# Generated by Django 5.0.3 on 2024-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_placepost_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placepost',
            old_name='recommended',
            new_name='vote',
        ),
        migrations.AddField(
            model_name='placepost',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placepost',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='placepost',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='placepost',
            name='place_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
