# Generated by Django 5.0.3 on 2024-04-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_initial'),
        ('place', '0003_rename_recommended_placepost_vote_placepost_address_and_more'),
    ]

    operations = [
    ]
