# Generated by Django 5.0.3 on 2024-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_merge_20240417_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placepost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='placepost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placepost',
            name='vote',
        ),
        migrations.AlterField(
            model_name='placepost',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='placepost',
            name='place_id',
            field=models.CharField(max_length=30),
        ),
    ]
