# Generated by Django 5.0.3 on 2024-04-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('user_region1', models.CharField(blank=True, max_length=100, null=True)),
                ('user_region2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
