# Generated by Django 5.0.3 on 2024-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_pw',
            field=models.CharField(max_length=15),
        ),
    ]
