# Generated by Django 5.0.3 on 2024-04-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_question_modify_date_question_question_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
    ]
